name: WeaponsPlugin
version: 1.0.0
main: com.bartilibiaz.weaponsplugin.WeaponsPlugin
description: Advanced Weapons System with YAML Configuration
api-version: 1.13

commands:
  weaponsZ:
    description: Weapons plugin commands
    usage: /weaponsZ reload
    aliases:
      - wz
      - weapons

permissions:
  weapons.admin:
    description: Access to /weaponsZ admin commands
    default: op
